services:
  db-api:
    build:
      context: ./packages/db-api
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    volumes:
      - ./packages/db-api:/usr/src/app
      - /usr/src/app/node_modules

  jobs:
    build:
      context: ./packages/jobs
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./packages/jobs:/usr/src/app
      - /usr/src/app/node_modules

  web-app:
    build:
      context: ./packages/web-app
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db-api
      - redis
    volumes:
      - ./packages/web-app:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  redis:
      image: redis:7-alpine
      ports:
        - "6379:6379"
      volumes:
        - redis-data:/data


volumes:
  postgres-data:
  redis-data:
